#!/bin/bash
echo $1 "+++++" $2 #here you can pass arguments through exceution $1==> first argument 
sleep 2

echo "And Procceser ID is: $$"

sleep 3
greeting="Hello There, "
echo $USER

echo $SECONDS


name="kazamelo"
echo ${greeting} ${name} 
